# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=22.4.1
FROM node:22.19.0-alpine3.21 as base

LABEL fly_launch_runtime="Next.js"

# Next.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"


# Throw-away build stage to reduce size of final image
FROM base as build

# Install node modules
COPY package-lock.json package.json ./
RUN npm ci --include=dev --legacy-peer-deps

# Copy application code
COPY . .

# Build application
RUN npm run build

# Remove development dependencies
RUN npm prune --omit=dev --legacy-peer-deps


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app/.next/standalone /app
COPY --from=build /app/.next/static /app/.next/static
COPY --from=build /app/public /app/public

# These files are needed for PWA functionality
# COPY --from=build /app/.next/service-worker.js /app/.next/
# COPY --from=build /app/.next/workbox-*.js /app/.next/
# COPY --from=build /app/server.js /app/


# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["sh", "-c", "node server.js"]
