services:
  nextjs:
    build:
      context: .
      dockerfile: Localdockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - TENANT_API_KEY=${TENANT_API_KEY}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST}
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
      - NODE_ENV=${NODE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PLAID_REDIRECT_URI=${PLAID_REDIRECT_URI}
      - BUCKET_NAME=${BUCKET_NAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_SITE_ACCESS_CODE=${NEXT_PUBLIC_SITE_ACCESS_CODE}
      - AI_URL=${AI_URL}
      - MODEL_ID=${MODEL_ID}
      - SITE_URL=${SITE_URL}
      - ENCRYPTION_KEY_1=${ENCRYPTION_KEY_1}
      - NEXT_PUBLIC_MIXPANEL_TOKEN=${NEXT_PUBLIC_MIXPANEL_TOKEN}
  consumer:
    build:
      context: .
      dockerfile: Localdockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    command: npm run consume
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - TENANT_API_KEY=${TENANT_API_KEY}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST}
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
      - NODE_ENV=${NODE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PLAID_REDIRECT_URI=${PLAID_REDIRECT_URI}
      - BUCKET_NAME=${BUCKET_NAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MODEL_ID=${MODEL_ID}
      - NEXT_PUBLIC_SITE_ACCESS_CODE=${NEXT_PUBLIC_SITE_ACCESS_CODE}
      - ENCRYPTION_KEY_1=${ENCRYPTION_KEY_1}
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  playwright:
    build:
      context: .
      dockerfile: playwright.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ['true']
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 4G
        reservations:
          cpus: '2'
    depends_on:
      - nextjs
    environment:
      - CI=true
      - BASE_URL=http://nextjs:3000
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - TENANT_API_KEY=${TENANT_API_KEY}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST}
      - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
      - NODE_ENV=${NODE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PLAID_REDIRECT_URI=${PLAID_REDIRECT_URI}
      - BUCKET_NAME=${BUCKET_NAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MODEL_ID=${MODEL_ID}
      - NEXT_PUBLIC_SITE_ACCESS_CODE=${NEXT_PUBLIC_SITE_ACCESS_CODE}
      - ENCRYPTION_KEY_1=${ENCRYPTION_KEY_1}
