# fly.toml app configuration file generated for fincapy-consumer on 2025-02-18T07:44:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fincapy-consumer'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile.consumer'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
