import fs from 'fs';

// Transaction types from domain/transaction.js
const transactionTypes = [
  'spending',
  'transfer',
  'credit_card_payment',
  'credit_card_refund',
  'debit_card_refund',
  'investment_transfer',
  'interest_income',
  'income',
];

// Sample category structure - expanded with various budgeting methodologies
const sampleCategories = [
  // Traditional needs/wants categories
  'needs.housing.rent',
  'needs.housing.mortgage',
  'needs.housing.utilities',
  'needs.food.groceries',
  'needs.food.dining_out',
  'needs.transportation.car_payment',
  'needs.transportation.gas',
  'needs.transportation.public_transit',
  'needs.health.insurance',
  'needs.health.medications',
  'wants.entertainment.streaming',
  'wants.entertainment.movies',
  'wants.shopping.clothing',
  'wants.shopping.electronics',
  'wants.travel.flights',
  'wants.travel.hotels',
  'income.salary',
  'income.bonus',
  'income.investment',
  'income.interest',

  // Conscious Spending Plan categories (Ramit Sethi)
  'fixed_costs.housing.rent',
  'fixed_costs.housing.mortgage',
  'fixed_costs.utilities.electricity',
  'fixed_costs.utilities.water',
  'fixed_costs.utilities.internet',
  'fixed_costs.utilities.phone',
  'fixed_costs.debt.student_loans',
  'fixed_costs.debt.personal_loans',
  'fixed_costs.insurance.health',
  'fixed_costs.insurance.auto',
  'fixed_costs.insurance.home',
  'fixed_costs.insurance.life',
  'fixed_costs.subscriptions.gym',
  'guilt_free.entertainment.dining',
  'guilt_free.entertainment.concerts',
  'guilt_free.shopping.clothing',
  'guilt_free.shopping.gadgets',
  'guilt_free.travel.hotels',
  'guilt_free.travel.experiences',

  // YNAB (You Need A Budget) style categories
  'ynab.immediate_obligations.rent',
  'ynab.immediate_obligations.electric',
  'ynab.immediate_obligations.water',
  'ynab.immediate_obligations.groceries',
  'ynab.true_expenses.auto_maintenance',
  'ynab.true_expenses.home_maintenance',
  'ynab.true_expenses.medical',
  'ynab.true_expenses.clothing',
  'ynab.debt_payments.student_loan',
  'ynab.debt_payments.auto_loan',
  'ynab.debt_payments.credit_card',
  'ynab.quality_of_life.dining_out',
  'ynab.quality_of_life.entertainment',
  'ynab.quality_of_life.fitness',
  'ynab.just_for_fun.vacation',
  'ynab.just_for_fun.spending_money',

  // 50/30/20 Budget categories
  'fifty_thirty_twenty.needs.housing',
  'fifty_thirty_twenty.needs.groceries',
  'fifty_thirty_twenty.needs.transportation',
  'fifty_thirty_twenty.needs.healthcare',
  'fifty_thirty_twenty.needs.minimum_debt_payments',
  'fifty_thirty_twenty.wants.dining_out',
  'fifty_thirty_twenty.wants.entertainment',
  'fifty_thirty_twenty.wants.shopping',
  'fifty_thirty_twenty.wants.hobbies',
  'fifty_thirty_twenty.wants.travel',

  // Zero-based budget categories
  'zero_based.giving.charity',
  'zero_based.giving.gifts',
  'zero_based.housing.mortgage',
  'zero_based.housing.utilities',
  'zero_based.transportation.car_payment',
  'zero_based.transportation.gas',
  'zero_based.food.groceries',
  'zero_based.food.restaurants',
  'zero_based.personal.clothing',
  'zero_based.personal.phone',
  'zero_based.personal.fun_money',
  'zero_based.health.insurance',
  'zero_based.health.gym',
  'zero_based.debt.credit_cards',
  'zero_based.debt.student_loans',

  // Additional income categories
  'income.freelance',
  'income.rental',
  'income.gifts',
  'income.tax_refund',
  'income.side_hustle',
];

// Sample merchants by category (expanded)
const merchantsByCategory = {
  // Housing related
  'needs.housing.rent': [
    'Apartment Management Inc',
    'Housing Corp',
    'Property Managers LLC',
    'City Rentals',
    'Campus Housing',
    'Urban Apartments',
    'Metropolitan Leasing',
  ],
  'needs.housing.mortgage': [
    'Chase Mortgage',
    'Wells Fargo Home Loans',
    'Bank of America Mortgage',
    'Quicken Loans',
    'Rocket Mortgage',
    'Truist Mortgage',
    'PNC Mortgage',
  ],
  'needs.housing.utilities': [
    'City Electric',
    'Water Authority',
    'Gas Company',
    'Internet Provider',
    'Waste Management',
    'Solar City',
    'County Utilities',
    'Spectrum',
    'Comcast',
    'AT&T',
  ],
  'fixed_costs.housing.rent': [
    'Equity Residential',
    'AvalonBay',
    'Essex Property Trust',
    'Camden Property',
    'Greystar Apartments',
    'Bell Partners',
    'MAA Apartments',
  ],
  'fixed_costs.housing.mortgage': [
    'JP Morgan Chase',
    'Citi Mortgage',
    'Freedom Mortgage',
    'Caliber Home Loans',
    'LoanDepot',
    'Guild Mortgage',
    'Mr. Cooper',
  ],
  'fixed_costs.utilities.electricity': [
    'Duke Energy',
    'ConEdison',
    'PG&E',
    'Southern California Edison',
    'Dominion Energy',
    'Xcel Energy',
    'NRG Energy',
  ],
  'fixed_costs.utilities.water': [
    'American Water',
    'Municipal Water',
    'City Water Dept',
    'County Water Authority',
    'Water Works',
    'Metropolitan Water District',
    'Rural Water Association',
  ],
  'fixed_costs.utilities.internet': [
    'Comcast',
    'Verizon Fios',
    'AT&T Internet',
    'Spectrum',
    'Cox Communications',
    'CenturyLink',
    'Frontier',
    'Google Fiber',
    'Xfinity',
  ],
  'fixed_costs.utilities.phone': [
    'Verizon Wireless',
    'AT&T Mobility',
    'T-Mobile',
    'Sprint',
    'Google Fi',
    'Mint Mobile',
    'Cricket Wireless',
    'Metro by T-Mobile',
    'Consumer Cellular',
  ],

  // Food related
  'needs.food.groceries': [
    'Whole Foods',
    'Safeway',
    "Trader Joe's",
    'Kroger',
    'Aldi',
    'Publix',
    'Wegmans',
    'Food Lion',
    'Albertsons',
    'Giant Eagle',
    'Sprouts',
    'Costco',
    'Target Grocery',
    'Walmart Grocery',
  ],
  'needs.food.dining_out': [
    'McDonalds',
    'Chipotle',
    'Olive Garden',
    'Local Restaurant',
    'Starbucks',
    'Panera Bread',
    "Applebee's",
    "Chili's",
    'The Cheesecake Factory',
    'Subway',
    'Taco Bell',
    'Burger King',
    'Five Guys',
    'Shake Shack',
    'Sweetgreen',
    'Panda Express',
  ],
  'guilt_free.entertainment.dining': [
    "Ruth's Chris",
    'Capital Grille',
    'The French Laundry',
    'Nobu',
    'Eleven Madison Park',
    'Per Se',
    'Le Bernardin',
    'Masa',
    'Alinea',
    'Daniel',
    'Jean-Georges',
    'Hakkasan',
    'Momofuku',
    'Craft',
    'Daniel Boulud',
  ],
  'ynab.quality_of_life.dining_out': [
    'Texas Roadhouse',
    'Outback Steakhouse',
    'Red Lobster',
    "P.F. Chang's",
    'Bonefish Grill',
    "Fleming's",
    'Seasons 52',
    'Benihana',
    'Red Robin',
    "BJ's Restaurant",
    "Denny's",
    'IHOP',
    'Waffle House',
    'Cracker Barrel',
  ],
  'zero_based.food.groceries': [
    'H-E-B',
    'Meijer',
    'Fresh Market',
    'ShopRite',
    'Piggly Wiggly',
    'Winn-Dixie',
    'Vons',
    'Harris Teeter',
    'Ralphs',
    'Hy-Vee',
    "Raley's",
    'Jewel-Osco',
    'Save Mart',
    'Food4Less',
  ],
  'zero_based.food.restaurants': [
    'Buffalo Wild Wings',
    "Dunkin'",
    'Pizza Hut',
    "Domino's",
    "Papa John's",
    'KFC',
    "Wendy's",
    'Jack in the Box',
    'In-N-Out Burger',
    'Whataburger',
    'Popeyes',
    'Chick-fil-A',
    "Jimmy John's",
    "Jersey Mike's",
  ],

  // Transportation related
  'needs.transportation.car_payment': [
    'Toyota Financial',
    'Honda Financial',
    'Ford Credit',
    'GM Financial',
    'BMW Financial Services',
    'Mercedes-Benz Financial',
    'Nissan Motor Acceptance',
    'Hyundai Motor Finance',
    'Volkswagen Credit',
    'Subaru Motors Finance',
    'Audi Financial Services',
    'Kia Motors Finance',
  ],
  'needs.transportation.gas': [
    'Shell',
    'Exxon',
    'Chevron',
    'BP',
    'Circle K',
    'Marathon',
    'Sunoco',
    'Valero',
    'Phillips 66',
    'QuikTrip',
    'RaceTrac',
    'Costco Gas',
    "Sam's Club Gas",
    'Wawa',
    'Cumberland Farms',
    'ARCO',
  ],
  'needs.transportation.public_transit': [
    'Metro Transit',
    'Uber',
    'Lyft',
    'City Bus',
    'Subway',
    'Amtrak',
    'MTA',
    'BART',
    'CTA',
    'MARTA',
    'SEPTA',
    'Metro',
    'Path Train',
    'TriMet',
    'Capital Bikeshare',
    'Lime',
    'Bird',
    'Spin',
  ],
  'fixed_costs.debt.student_loans': [
    'Great Lakes',
    'Nelnet',
    'Navient',
    'FedLoan Servicing',
    'Sallie Mae',
    'Discover Student Loans',
    'SoFi',
    'Earnest',
    'CommonBond',
    'MOHELA',
    'EdFinancial Services',
    'Ascent',
    'Laurel Road',
  ],
  'fifty_thirty_twenty.transportation.needs': [
    'AAA',
    'DMV',
    'Registration Renewal',
    'Parking Fee',
    'Highway Toll',
    'Zipcar',
    'Enterprise Rental',
    'Hertz',
    'National Car Rental',
    'Scooter Rental',
    'City Parking Meter',
    'Parking Garage',
  ],

  // Health related
  'needs.health.insurance': [
    'Blue Cross',
    'United Healthcare',
    'Kaiser Permanente',
    'Cigna',
    'Aetna',
    'Humana',
    'Anthem',
    'Medicare',
    'Medicaid',
    'Oscar Health',
    'Bright Health',
    'Ambetter',
    'Molina Healthcare',
  ],
  'needs.health.medications': [
    'Walgreens',
    'CVS Pharmacy',
    'Rite Aid',
    'Express Scripts',
    'OptumRx',
    'Costco Pharmacy',
    'Walmart Pharmacy',
    'Kroger Pharmacy',
    'Mail Order Pharmacy',
    'Capsule',
    'PillPack',
    'GoodRx',
    'Amazon Pharmacy',
  ],
  'fixed_costs.insurance.health': [
    'Blue Shield',
    'Centene',
    'Health Net',
    'Wellcare',
    'UnitedHealthOne',
    'BCBS Federal',
    'Medi-Cal',
    'Tricare',
    'Magellan Health',
    'Cigna-Express Scripts',
    'GuideWell',
    'Highmark Health',
    'HealthPartners',
  ],
  'fixed_costs.insurance.auto': [
    'Geico',
    'Progressive',
    'State Farm',
    'Allstate',
    'Liberty Mutual',
    'Farmers Insurance',
    'Nationwide',
    'USAA',
    'Travelers',
    'Mercury',
    'The General',
    'American Family',
    'Erie Insurance',
  ],
  'fixed_costs.insurance.home': [
    'State Farm',
    'Allstate',
    'Liberty Mutual',
    'Geico',
    'Nationwide',
    'Farmers',
    'Travelers',
    'American Family',
    'Erie Insurance',
    'Amica Mutual',
    'Chubb',
    'USAA',
    'Lemonade',
    'Hippo Insurance',
  ],
  'ynab.true_expenses.medical': [
    'Quest Diagnostics',
    'LabCorp',
    'OneMedical',
    'Cleveland Clinic',
    'Mayo Clinic',
    'Johns Hopkins',
    'Memorial Sloan Kettering',
    'NYU Langone',
    'UCSF Medical Center',
    'Massage Therapy',
    'Chiropractor',
    'Psychiatrist',
    'Therapist',
  ],

  // Entertainment related
  'wants.entertainment.streaming': [
    'Netflix',
    'Hulu',
    'Disney+',
    'Spotify',
    'Apple TV+',
    'HBO Max',
    'Amazon Prime Video',
    'Paramount+',
    'Peacock',
    'YouTube Premium',
    'Sling TV',
    'fuboTV',
    'Discovery+',
    'Crunchyroll',
    'Tidal',
    'Apple Music',
    'Audible',
    'PlayStation Now',
    'Xbox Game Pass',
    'Nintendo Switch Online',
  ],
  'wants.entertainment.movies': [
    'AMC Theaters',
    'Regal Cinemas',
    'Cinemark',
    'Alamo Drafthouse',
    'Marcus Theatres',
    'Landmark Theatres',
    'IMAX',
    'Fandango',
    'Atom Tickets',
    'Film Festival',
    'Drive-In Theater',
    'Studio Movie Grill',
    'Arclight Cinemas',
  ],
  'guilt_free.entertainment.concerts': [
    'Ticketmaster',
    'Live Nation',
    'StubHub',
    'SeatGeek',
    'AXS',
    'VividSeats',
    'Eventbrite',
    'Bandsintown',
    'Symphony Orchestra',
    'Opera House',
    'Music Festival',
    'Concert Hall',
    'Jazz Club',
    'Broadway Tickets',
    'Comedy Club',
  ],
  'ynab.quality_of_life.entertainment': [
    "Dave & Buster's",
    'TopGolf',
    'Escape Room',
    'Bowling Alley',
    'Laser Tag',
    'Zoo Admission',
    'Aquarium',
    'Museum Entry',
    'Theme Park',
    'Water Park',
    'Mini Golf',
    'Arcade',
    'Karaoke Bar',
    'Painting Class',
    'Pottery Studio',
  ],
  'fixed_costs.subscriptions.gym': [
    'Planet Fitness',
    'LA Fitness',
    "Gold's Gym",
    'Equinox',
    'Lifetime Fitness',
    'Anytime Fitness',
    'Crunch Fitness',
    'Orange Theory',
    'CrossFit',
    'SoulCycle',
    'Peloton',
    'YMCA',
    "Barry's Bootcamp",
    'Pure Barre',
    'CorePower Yoga',
    'Fitness Connection',
  ],

  // Shopping related
  'wants.shopping.clothing': [
    'H&M',
    'Nordstrom',
    'Old Navy',
    "Macy's",
    'TJ Maxx',
    'Gap',
    'Banana Republic',
    'Lululemon',
    'Nike',
    'Adidas',
    'Under Armour',
    'J.Crew',
    'Uniqlo',
    'Express',
    'Zara',
    'American Eagle',
    'Asos',
    'Anthropologie',
    'Urban Outfitters',
    'REI',
    'The North Face',
    'Patagonia',
    'Abercrombie & Fitch',
    'Free People',
  ],
  'wants.shopping.electronics': [
    'Best Buy',
    'Apple Store',
    'Amazon',
    'Newegg',
    'Micro Center',
    'Microsoft Store',
    'Samsung Store',
    "Fry's Electronics",
    'B&H Photo Video',
    'GameStop',
    'Costco Electronics',
    'Target Electronics',
    'Walmart Electronics',
    'Bose Store',
    'Sony Store',
    'Verizon Store',
    'AT&T Store',
    'T-Mobile Store',
  ],
  'guilt_free.shopping.clothing': [
    'Gucci',
    'Louis Vuitton',
    'Chanel',
    'Prada',
    'Burberry',
    'Hermes',
    'Versace',
    'Dior',
    'Armani',
    'Saint Laurent',
    'Balenciaga',
    'Fendi',
    'Ralph Lauren',
    'Brooks Brothers',
    'Coach',
    'Kate Spade',
    'Michael Kors',
    'Hugo Boss',
    'Saks Fifth Avenue',
    'Neiman Marcus',
    "Bloomingdale's",
    'Bergdorf Goodman',
  ],
  'guilt_free.shopping.gadgets': [
    'Apple',
    'Samsung',
    'Sony',
    'Bose',
    'Sonos',
    'Bang & Olufsen',
    'Leica',
    'Canon',
    'Nikon',
    'DJI',
    'Alienware',
    'Razer',
    'Dyson',
    'GoPro',
    'Oculus',
    'Bowers & Wilkins',
    'Audio-Technica',
    'Breville',
    'Vitamix',
  ],
  'zero_based.personal.clothing': [
    "Kohl's",
    'JCPenney',
    "Dillard's",
    'Ross',
    "Marshall's",
    'Burlington',
    'Target Clothing',
    'Walmart Clothing',
    "Lands' End",
    'L.L. Bean',
    'Eddie Bauer',
    'Columbia',
    'Carhartt',
    "Levi's",
    'Dockers',
    "Carter's",
    "OshKosh B'gosh",
    'Old Navy',
  ],

  // Travel related
  'wants.travel.flights': [
    'United Airlines',
    'Delta Airlines',
    'Southwest',
    'American Airlines',
    'JetBlue',
    'Alaska Airlines',
    'Spirit Airlines',
    'Frontier Airlines',
    'Allegiant Air',
    'Air Canada',
    'British Airways',
    'Lufthansa',
    'Emirates',
    'Qatar Airways',
    'Singapore Airlines',
    'Cathay Pacific',
    'ANA',
    'Expedia Flights',
    'Kayak',
    'Orbitz',
  ],
  'wants.travel.hotels': [
    'Marriott',
    'Hilton',
    'Holiday Inn',
    'Airbnb',
    'Hyatt',
    'Best Western',
    'Choice Hotels',
    'InterContinental',
    'Wyndham',
    'Four Seasons',
    'Ritz-Carlton',
    'W Hotels',
    'Hampton Inn',
    'Courtyard by Marriott',
    'Embassy Suites',
    'Motel 6',
    'Super 8',
    'Days Inn',
    'VRBO',
    'Booking.com',
    'Hotels.com',
    'Expedia Hotels',
  ],
  'guilt_free.travel.hotels': [
    'St. Regis',
    'Park Hyatt',
    'Aman Resorts',
    'Mandarin Oriental',
    'Peninsula Hotels',
    'Belmond',
    'One&Only Resorts',
    'Six Senses',
    'Waldorf Astoria',
    'Bvlgari Hotels',
    'Rosewood',
    'Conrad',
    'Luxury Collection',
    'Viceroy',
    'Fairmont',
    'JW Marriott',
    'Ritz-Carlton Reserve',
  ],
  'guilt_free.travel.experiences': [
    'Virtuoso Travel',
    'Abercrombie & Kent',
    'Backroads',
    'National Geographic Expeditions',
    'G Adventures',
    'Intrepid Travel',
    'Viking Cruises',
    'Royal Caribbean',
    'Disney Cruise Line',
    'Lindblad Expeditions',
    'Crystal Cruises',
    'Tauck Tours',
    'REI Adventures',
    'Butterfield & Robinson',
    'Helicopter Tours',
    'Private Jet Charter',
    'Hot Air Balloon Ride',
  ],
  'fifty_thirty_twenty.wants.travel': [
    'Travelocity',
    'Priceline',
    'Trivago',
    'Hotwire',
    'Tripadvisor',
    'Lonely Planet',
    'Rick Steves',
    'Viator',
    'GetYourGuide',
    'Travel Insurance',
    'Airport Lounge',
    'Currency Exchange',
    'Hostel World',
    'Vacation Rental',
  ],

  // Income related
  'income.salary': [
    'Employer Direct Deposit',
    'Payroll',
    'Company Inc Payroll',
    'Salary Payment',
    'Wage Payment',
    'HR Payroll',
    'ADP Payroll',
    'Gusto Payroll',
    'Paychex',
    'Workday Payroll',
    'Zenefits',
    'Paylocity',
    'UltiPro Payroll',
  ],
  'income.bonus': [
    'Annual Bonus',
    'Performance Bonus',
    'Holiday Bonus',
    'Quarterly Bonus',
    'Signing Bonus',
    'Year-End Bonus',
    'Profit Sharing',
    'Commission',
    'Employee Referral Bonus',
    'Sales Commission',
    'Goal Achievement Bonus',
  ],
  'income.investment': [
    'Dividend Payment',
    'Stock Sale',
    'Investment Return',
    'Capital Gains',
    'P2P Lending Interest',
    'REIT Distribution',
    'Bond Interest',
    'ETF Distribution',
    'Mutual Fund Distribution',
    'Stock Option Exercise',
    'Crypto Sale',
    'Private Equity Distribution',
  ],
  'income.interest': [
    'Savings Interest',
    'CD Interest',
    'Bond Interest',
    'Money Market Interest',
    'High-Yield Savings',
    'T-Bill Interest',
    'Municipal Bond Interest',
    'Corporate Bond Interest',
    'Treasury Bond Interest',
    'Certificate of Deposit Maturity',
  ],
  'income.freelance': [
    'Upwork Payment',
    'Fiverr Payment',
    'Freelancer.com',
    'Client Payment',
    'Consulting Fee',
    'Contract Work',
    'Project Payment',
    'Gig Payment',
    'Tutoring',
    'Coaching',
    'Consulting Services',
    'Technical Services',
    'Writing Services',
  ],

  // Other categories
  'zero_based.giving.charity': [
    'United Way',
    'Red Cross',
    'Salvation Army',
    'Habitat for Humanity',
    "St. Jude Children's Hospital",
    'American Cancer Society',
    'World Wildlife Fund',
    'UNICEF',
    'Feeding America',
    'Doctors Without Borders',
    'Local Food Bank',
    'Church Donation',
    'GoFundMe',
    'Kickstarter',
    'Patreon',
  ],
  'ynab.just_for_fun.vacation': [
    'All-Inclusive Resort',
    'Ski Resort',
    'Disneyland',
    'Disney World',
    'Universal Studios',
    'Cruise Line',
    'Beach Resort',
    'Mountain Lodge',
    'Family Vacation',
    'Couples Retreat',
    'Road Trip',
    'National Park',
    'Sightseeing Tour',
    'Guided Tour',
  ],
  // Additional missing categories
  'fixed_costs.debt.personal_loans': [
    'Lending Club',
    'Prosper',
    'Marcus by Goldman Sachs',
    'OneMain Financial',
    'Upstart',
    'Best Egg',
    'LightStream',
    'Avant',
    'Payoff',
  ],
  'fixed_costs.insurance.life': [
    'Northwestern Mutual',
    'New York Life',
    'Prudential',
    'State Farm Life',
    'MassMutual',
    'Guardian Life',
    'Transamerica',
    'John Hancock',
    'Lincoln Financial',
  ],
  'ynab.immediate_obligations.rent': [
    'Rental Corp',
    'Apartment Services',
    'Residential Leasing',
    'Property Management',
    'Rent Payment',
    'Housing Authority',
    'PMI Properties',
    'Tenant Portal',
  ],
  'ynab.immediate_obligations.electric': [
    'Electric Company',
    'Power Services',
    'Utility Payment',
    'Energy Provider',
    'Electric Cooperative',
    'Municipal Electric',
    'Regional Power',
  ],
  'ynab.immediate_obligations.water': [
    'Water Services',
    'Water Utility',
    'City Water',
    'H2O Provider',
    'Water District',
    'Aqua Services',
    'Municipal Water Dept',
  ],
  'ynab.immediate_obligations.groceries': [
    'Family Supermarket',
    'Local Grocery',
    'Fresh Foods Market',
    'Organic Market',
    'Neighborhood Grocery',
    'Farmers Market',
    'Community Foods',
  ],
  'ynab.true_expenses.auto_maintenance': [
    'Auto Shop',
    'Mechanic Services',
    'Car Repair Center',
    'Vehicle Maintenance',
    'Midas',
    'Jiffy Lube',
    'Firestone',
    'Meineke',
    'Pep Boys',
  ],
  'ynab.true_expenses.home_maintenance': [
    'Home Depot',
    'Lowes',
    'Ace Hardware',
    'Handyman Services',
    'Plumber',
    'Electrician',
    'HVAC Services',
    'Pest Control',
    'Lawn Care',
  ],
  'ynab.true_expenses.clothing': [
    'Clothing Store',
    'Fashion Outlet',
    'Apparel Shop',
    'Wardrobe Essentials',
    'Basics Clothing',
    'Seasonal Apparel',
    'Clothing Essentials',
  ],
  'ynab.debt_payments.student_loan': [
    'Student Loan Servicer',
    'Education Loan',
    'Student Loan Payment',
    'Federal Loan Servicing',
    'College Loan',
    'Student Debt Center',
    'Education Finance',
  ],
  'ynab.debt_payments.auto_loan': [
    'Auto Loan Center',
    'Car Finance',
    'Vehicle Loan',
    'Auto Finance',
    'Auto Lender',
    'Car Loan Services',
    'Vehicle Financing',
  ],
  'ynab.debt_payments.credit_card': [
    'Credit Card Payment',
    'Card Services',
    'Credit Account',
    'Card Statement Payment',
    'Credit Payment Center',
    'Card Balance Payment',
    'Credit Services',
  ],
  'ynab.quality_of_life.fitness': [
    'Fitness Studio',
    'Local Gym',
    'Workout Center',
    'Training Facility',
    'Fitness Classes',
    'Yoga Studio',
    'Pilates Center',
    'Crossfit Box',
  ],
  'ynab.just_for_fun.spending_money': [
    'Fun Budget',
    'Entertainment Fund',
    'Personal Allowance',
    'Discretionary Spending',
    'Fun Money',
    'Spending Cash',
    'Personal Fund',
  ],
  'fifty_thirty_twenty.needs.housing': [
    'Housing Payment',
    'Shelter Costs',
    'Living Space',
    'Housing Essentials',
    'Primary Residence',
    'Dwelling Payment',
    'Housing Expense',
  ],
  'fifty_thirty_twenty.needs.groceries': [
    'Grocery Essentials',
    'Food Necessities',
    'Basic Groceries',
    'Kitchen Staples',
    'Essential Food',
    'Pantry Basics',
    'Grocery Needs',
  ],
  'fifty_thirty_twenty.needs.transportation': [
    'Essential Transport',
    'Commute Costs',
    'Necessary Travel',
    'Transport Basics',
    'Work Transport',
    'Required Travel',
    'Basic Mobility',
  ],
  'fifty_thirty_twenty.needs.healthcare': [
    'Essential Healthcare',
    'Medical Necessity',
    'Health Basics',
    'Required Medicine',
    'Medical Essentials',
    'Necessary Treatment',
    'Basic Health Services',
  ],
  'fifty_thirty_twenty.needs.minimum_debt_payments': [
    'Minimum Payment',
    'Required Debt Payment',
    'Basic Obligation',
    'Minimum Balance',
    'Debt Minimum',
    'Required Payment',
    'Base Debt Payment',
  ],
  'fifty_thirty_twenty.wants.dining_out': [
    'Restaurant Leisure',
    'Dining Experience',
    'Food Enjoyment',
    'Eating Out',
    'Social Dining',
    'Restaurant Treat',
    'Dining Adventure',
  ],
  'fifty_thirty_twenty.wants.entertainment': [
    'Fun Activities',
    'Recreation Choice',
    'Leisure Events',
    'Entertainment Option',
    'Recreation Activity',
    'Enjoyment Service',
    'Amusement Choice',
  ],
  'fifty_thirty_twenty.wants.shopping': [
    'Discretionary Purchase',
    'Non-Essential Shopping',
    'Want-Based Buying',
    'Lifestyle Purchase',
    'Optional Shopping',
    'Desire Purchase',
    'Non-Necessity Buy',
  ],
  'fifty_thirty_twenty.wants.hobbies': [
    'Hobby Shop',
    'Craft Store',
    'Pastime Supplies',
    'Hobby Materials',
    'Leisure Activity',
    'Special Interest Store',
    'Recreational Supplies',
  ],
  'fifty_thirty_twenty.wants.travel': [
    'Pleasure Travel',
    'Vacation Choice',
    'Leisure Journey',
    'Holiday Trip',
    'Recreational Travel',
    'Getaway Experience',
    'Optional Excursion',
  ],
  'zero_based.giving.gifts': [
    'Gift Shop',
    'Present Purchase',
    'Gift Store',
    'Gift Registry',
    'Celebration Gifts',
    'Present Selection',
    'Holiday Presents',
  ],
  'zero_based.housing.mortgage': [
    'Home Loan Payment',
    'Mortgage Services',
    'Property Financing',
    'Home Finance',
    'Mortgage Center',
    'House Payment',
    'Property Loan',
  ],
  'zero_based.housing.utilities': [
    'Home Utilities',
    'Household Services',
    'Essential Services',
    'Home Services',
    'Residential Utilities',
    'Home Essentials',
    'Basic Utilities',
  ],
  'zero_based.transportation.car_payment': [
    'Vehicle Payment',
    'Auto Financing',
    'Car Payment Center',
    'Vehicle Financing',
    'Auto Payment',
    'Car Loan Payment',
    'Vehicle Loan Center',
  ],
  'zero_based.transportation.gas': [
    'Fuel Center',
    'Gas Station',
    'Petrol Station',
    'Fuel Services',
    'Energy Station',
    'Filling Station',
    'Fuel Stop',
  ],
  'zero_based.personal.phone': [
    'Phone Provider',
    'Mobile Services',
    'Wireless Company',
    'Cell Service',
    'Telephone Company',
    'Phone Carrier',
    'Mobile Plan',
  ],
  'zero_based.personal.fun_money': [
    'Entertainment Fund',
    'Personal Enjoyment',
    'Fun Budget',
    'Leisure Money',
    'Personal Recreation',
    'Discretionary Fund',
    'Entertainment Budget',
  ],
  'zero_based.health.insurance': [
    'Health Coverage',
    'Insurance Provider',
    'Medical Insurance',
    'Health Plan',
    'Medical Coverage',
    'Healthcare Policy',
    'Insurance Plan',
  ],
  'zero_based.health.gym': [
    'Fitness Center',
    'Workout Facility',
    'Health Club',
    'Exercise Center',
    'Training Facility',
    'Gym Membership',
    'Fitness Club',
  ],
  'zero_based.debt.credit_cards': [
    'Card Payment',
    'Credit Services',
    'Card Balance',
    'Revolving Account',
    'Credit Account',
    'Card Settlement',
    'Credit Management',
  ],
  'zero_based.debt.student_loans': [
    'Education Debt',
    'Student Finance',
    'Education Loan',
    'College Debt',
    'Student Debt Services',
    'Academic Loans',
    'Education Credit',
  ],
  'income.rental': [
    'Rental Income',
    'Property Revenue',
    'Rental Payment',
    'Tenant Payment',
    'Property Income',
    'Rent Revenue',
    'Lease Income',
  ],
  'income.gifts': [
    'Gift Income',
    'Personal Gift',
    'Money Gift',
    'Received Present',
    'Cash Gift',
    'Gift Payment',
    'Monetary Present',
  ],
  'income.tax_refund': [
    'Tax Return',
    'IRS Refund',
    'Tax Rebate',
    'Government Refund',
    'Tax Office Return',
    'Tax Payment Return',
    'Tax Credit Refund',
  ],
  'income.side_hustle': [
    'Side Business',
    'Extra Income',
    'Gig Work',
    'Part-time Income',
    'Secondary Job',
    'Side Project',
    'Freelance Income',
    'Hustle Payment',
  ],
};

// Account types and subtypes
const accountTypes = ['depository', 'credit', 'loan', 'investment'];
const accountSubtypes = {
  depository: ['checking', 'savings', 'hsa', 'cd', 'money market'],
  credit: ['credit card', 'line of credit'],
  loan: ['auto', 'mortgage', 'student', 'personal'],
  investment: ['401k', 'ira', 'brokerage', 'roth'],
};

function generateTransaction() {
  // generate a random number between 0 and the length of the sample categories
  const randomCategoryIndex = Math.floor(
    Math.random() * sampleCategories.length
  );
  const randomCategory = sampleCategories[randomCategoryIndex];

  // generate a random number between 0 and the length of the sample merchants
  const randomMerchantIndex = Math.floor(
    Math.random() * merchantsByCategory[randomCategory].length
  );
  const randomMerchant =
    merchantsByCategory[randomCategory][randomMerchantIndex];

  // generate a random amount between 0 and 1000
  const randomAmount = Math.floor(Math.random() * 1000);
}

// Generate the full dataset
function generateDataset(numRecords = 1000) {}

// Main function to generate and save dataset
function main() {
  // Check for missing categories
  const missingCategories = [];
  for (const category of sampleCategories) {
    if (!merchantsByCategory[category]) {
      missingCategories.push(category);
    }
  }

  console.log('Missing categories:', missingCategories);
  console.log(`Total categories: ${sampleCategories.length}`);
  console.log(
    `Categories with merchants: ${Object.keys(merchantsByCategory).length}`
  );
  console.log(`Missing categories count: ${missingCategories.length}`);

  const numRecords = process.argv[2] ? parseInt(process.argv[2]) : 5;
  console.log(`Generating ${numRecords} synthetic transaction records...`);

  const rawDataset = generateDataset(numRecords);

  // Format for Hugging Face AutoTrainer
  const formattedDataset = rawDataset.map((item) => {
    return [
      { content: JSON.stringify(item.prompt), role: 'user' },
      { content: JSON.stringify(item.output), role: 'assistant' },
    ];
  });

  // For the JSON file, create a more readable version with unpacked JSON
  const readableDataset = rawDataset.map((item) => {
    return [
      { content: item.prompt, role: 'user' },
      { content: item.output, role: 'assistant' },
    ];
  });

  // Save the readable dataset to a JSON file
  fs.writeFileSync(
    'synthetic_transaction_dataset.json',
    JSON.stringify(readableDataset, null, 2)
  );
  console.log(`Readable dataset saved to synthetic_transaction_dataset.json`);

  // Save the stringified version in JSONL format for Hugging Face
  const jsonlContent = formattedDataset
    .map((item) => JSON.stringify(item))
    .join('\n');
  fs.writeFileSync('synthetic_transaction_dataset.jsonl', jsonlContent);
  console.log(`Training dataset saved to synthetic_transaction_dataset.jsonl`);

  // Save both readable and training versions in the sample file
  const sampleData = {
    rawFormat: rawDataset[0],
    readableFormat: readableDataset[0],
    trainingFormat: formattedDataset[0],
  };
  fs.writeFileSync('sample_data.json', JSON.stringify(sampleData, null, 2));
  console.log(`Sample data saved to sample_data.json for inspection`);
}

main();
