import Head from 'next/head';
import './globals.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overscroll-none" suppressHydrationWarning>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover, minimal-ui"
        />
      </Head>
      <UserProvider>
        <body className="touch-none overscroll-none">{children}</body>
      </UserProvider>
    </html>
  );
}
