import Head from 'next/head';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overscroll-none" suppressHydrationWarning>
      <body className="touch-none overscroll-none">{children}</body>
    </html>
  );
}
