# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-web:
    name: Deploy web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t web:${{ github.sha }} -f Dockerfile.web .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: web:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-web.sarif'
          severity: 'CRITICAL,HIGH'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c fly.web.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-consumer:
    name: Deploy consumer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t consumer:${{ github.sha }} -f Dockerfile.consumer .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: consumer:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-consumer.sarif'
          severity: 'CRITICAL,HIGH'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c fly.consumer.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_CONSUMER_API_TOKEN }}
